name: Unity Windows Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        unityVersion: 2022.3.55f1c1
        targetPlatform: StandaloneWindows64

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: WindowsBuild
        path: build
